name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
