name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Want something new? Let us know!
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: Short summary of the feature.
      placeholder: "Add dark mode toggle"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What and why?
      placeholder: "I'd like to be able to..."
    validations:
      required: true
